export default [
    {
        no: 1,
        tanggal: '2019-02-13',
        user: 'Toni',
        jenis_pekerjaan: 'Pemeliharaan',
        kode_afdeling: 'A1',
        afdeling: 'A',
        blok: '1',
        luas: 12,
        luas_yang_dikerjakan: 12,
        luas_yang_diperiksa: 12,
        diperiksa_oleh: 'Pak Mandor',
    },
    {
        no: 2,
        tanggal: '2019-02-17',
        user: 'Toni',
        jenis_pekerjaan: 'Pemeliharaan',
        kode_afdeling: 'A2',
        afdeling: 'A',
        blok: '2',
        luas: 7,
        luas_yang_dikerjakan: 7,
        luas_yang_diperiksa: 7,
        diperiksa_oleh: 'Pak Mandor',
    },
    {
        no: 3,
        tanggal: '2019-02-27',
        user: 'Toni',
        jenis_pekerjaan: 'Pemeliharaan',
        kode_afdeling: 'B1',
        afdeling: 'B',
        blok: '1',
        luas: 10,
        luas_yang_dikerjakan: 10,
        luas_yang_diperiksa: 10,
        diperiksa_oleh: 'Pak Mandor',
    },
    {
        no: 4,
        tanggal: '2019-03-05',
        user: 'Toni',
        jenis_pekerjaan: 'Pemeliharaan',
        kode_afdeling: 'B2',
        afdeling: 'B',
        blok: '2',
        luas: 11,
        luas_yang_dikerjakan: 11,
        diperiksa_oleh: '',
    },
    {
        no: 5,
        tanggal: '2019-02-14',
        user: 'Maman',
        jenis_pekerjaan: 'Pemeliharaan',
        kode_afdeling: 'C1',
        afdeling: 'C',
        blok: '1',
        luas: 11,
        luas_yang_dikerjakan: 11,
        luas_yang_diperiksa: 11,
        diperiksa_oleh: 'Pak Mandor',
    },
    {
        no: 6,
        tanggal: '2019-02-18',
        user: 'Maman',
        jenis_pekerjaan: 'Pemeliharaan',
        kode_afdeling: 'C2',
        afdeling: 'C',
        blok: '2',
        luas: 8,
        luas_yang_dikerjakan: 8,
        luas_yang_diperiksa: 8,
        diperiksa_oleh: 'Pak Mandor',
    },
    {
        no: 7,
        tanggal: '2019-02-28',
        user: 'Maman',
        jenis_pekerjaan: 'Pemeliharaan',
        kode_afdeling: 'D1',
        afdeling: 'D',
        blok: '1',
        luas: 12,
        luas_yang_dikerjakan: 12,
        luas_yang_diperiksa: 11,
        diperiksa_oleh: 'Pak Mandor',
    },
    {
        no: 8,
        tanggal: '2019-03-06',
        user: 'Maman',
        jenis_pekerjaan: 'Pemeliharaan',
        kode_afdeling: 'D2',
        afdeling: 'D',
        blok: '2',
        luas: 11,
        luas_yang_dikerjakan: 11,
        diperiksa_oleh: '',
    },
    {
        no: 9,
        tanggal: '2019-03-11',
        user: 'Maman',
        jenis_pekerjaan: 'Pemeliharaan',
        kode_afdeling: 'D3',
        afdeling: 'D',
        blok: '3',
        luas: 9,
        luas_yang_dikerjakan: 0,
        diperiksa_oleh: '',
    },
    {
        no: 10,
        tanggal: '2019-03-11',
        user: 'Toni',
        jenis_pekerjaan: 'Pemeliharaan',
        kode_afdeling: 'A3',
        afdeling: 'A',
        blok: '3',
        luas: 10,
        luas_yang_dikerjakan: null,
        diperiksa_oleh: '',
    },
    {
        no: 11,
        tanggal: '2019-03-11',
        user: 'Toni',
        jenis_pekerjaan: 'Pemetikan',
        kode_afdeling: 'D4',
        afdeling: 'D',
        blok: '4',
        luas: 8,
        luas_yang_dikerjakan: null,
        diperiksa_oleh: '',
    },
    {
        no: 12,
        tanggal: '2019-03-11',
        user: '',
        jenis_pekerjaan: 'Pemetikan',
        kode_afdeling: 'B3',
        afdeling: 'B',
        blok: '3',
        luas: 12,
        luas_yang_dikerjakan: null,
        diperiksa_oleh: '',
    },
]